import 'package:easy_localization/easy_localization.dart';
import 'package:parkingson_key/src/models/keyboard_item.dart';

final keyboardLayout = [
  [
    KeyboardItem.char('b'),
    KeyboardItem.char('c'),
    KeyboardItem.char('d'),
    KeyboardItem.char('f'),
    KeyboardItem.char('g'),
    KeyboardItem.char('h'),
    KeyboardItem.char('j'),
    KeyboardItem.char('k'),
  ],
  [
    KeyboardItem.char('l'),
    KeyboardItem.char('ll'),
    KeyboardItem.char('m'),
    KeyboardItem.char('n'),
    KeyboardItem.char('ñ'),
    KeyboardItem.char('p'),
    KeyboardItem.char('q'),
    KeyboardItem.char('qu'),
  ],
  [
    KeyboardItem.char('r'),
    KeyboardItem.char('rr'),
    KeyboardItem.char('s'),
    KeyboardItem.char('t'),
    KeyboardItem.char('v'),
    KeyboardItem.char('w'),
    KeyboardItem.char('x'),
    KeyboardItem.char('y'),
    KeyboardItem.char('z'),
  ],
  [
    KeyboardItem.char('a'),
    KeyboardItem.char('e'),
    KeyboardItem.char('i'),
    KeyboardItem.char('o'),
    KeyboardItem.char('u'),
    KeyboardItem.char('  '),
    KeyboardItem.action('Sí'),
    KeyboardItem.action('No'),
  ],
  [

    KeyboardItem.dropdown(
      title: "KEYBOARD_numbers".tr(),
      items: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
      initialValue: '0',
      onChanged: (v) {},
      flex: 2,
    ),
    KeyboardItem.dropdown(
      title: "KEYBOARD_symbols".tr(),
      items: [
        ".",
        ",",
        ":",
        ";",
        "?",
        "!",
        "-",
        "_",
        "@",
        "#",
        "%",
        "&",
        "/",
        "+",
        "*",
      ],
      initialValue: '!',
      onChanged: (v) {},
      flex: 2,
    ),
  ],
];
