import 'package:parkingson_key/src/models/keyboard/keyboard_item.dart';
import 'package:parkingson_key/src/models/keyboard/keyboard_layout.dart';

final enQwertyKeyboardLayout = KeyboardLayout(
  id: 'en_qwerty',
  portrait: [
    [
      KeyboardItem.char('q'),
      KeyboardItem.char('w'),
      KeyboardItem.char('e'),
      KeyboardItem.char('r'),
      KeyboardItem.char('t'),
      KeyboardItem.char('y'),
      KeyboardItem.char('u'),
      KeyboardItem.char('i'),
      KeyboardItem.char('o'),
      KeyboardItem.char('p'),
    ],
    [
      KeyboardItem.char('a'),
      KeyboardItem.char('s'),
      KeyboardItem.char('d'),
      KeyboardItem.char('f'),
      KeyboardItem.char('g'),
      KeyboardItem.char('h'),
      KeyboardItem.char('j'),
      KeyboardItem.char('k'),
      KeyboardItem.char('l'),
    ],
    [
      KeyboardItem.char('z'),
      KeyboardItem.char('x'),
      KeyboardItem.char('c'),
      KeyboardItem.char('v'),
      KeyboardItem.char('b'),
      KeyboardItem.char('n'),
      KeyboardItem.char('m'),
      KeyboardItem.char('Yes'),
      KeyboardItem.char('No'),
      KeyboardItem.char('  '),
    ],
    [
      KeyboardItem.dropdown(
        title: 'KEYBOARD_symbols',
        items: ['!', '@', '#', '\$', '%', '^', '&', '*'],
      ),
      KeyboardItem.dropdown(
        title: 'KEYBOARD_numbers',
        items: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
      ),
    ],
  ],
  landscape: [
    [
      KeyboardItem.char('q'),
      KeyboardItem.char('w'),
      KeyboardItem.char('e'),
      KeyboardItem.char('r'),
      KeyboardItem.char('t'),
      KeyboardItem.char('y'),
      KeyboardItem.char('u'),
      KeyboardItem.char('i'),
      KeyboardItem.char('o'),
      KeyboardItem.char('p'),
    ],
    [
      KeyboardItem.char('a'),
      KeyboardItem.char('s'),
      KeyboardItem.char('d'),
      KeyboardItem.char('f'),
      KeyboardItem.char('g'),
      KeyboardItem.char('h'),
      KeyboardItem.char('j'),
      KeyboardItem.char('k'),
      KeyboardItem.char('l'),
    ],
    [
      KeyboardItem.char('z'),
      KeyboardItem.char('x'),
      KeyboardItem.char('c'),
      KeyboardItem.char('v'),
      KeyboardItem.char('b'),
      KeyboardItem.char('n'),
      KeyboardItem.char('m'),
      KeyboardItem.char('Yes'),
      KeyboardItem.char('No'),
      KeyboardItem.char('  '),
    ],
    [
      KeyboardItem.dropdown(
        title: 'KEYBOARD_symbols',
        items: ['!', '@', '#', '\$', '%', '^', '&', '*'],
      ),
      KeyboardItem.dropdown(
        title: 'KEYBOARD_numbers',
        items: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
      ),
    ],
  ],
);
